// FrontAngular/src/app/table/static-table/static-table.component.ts
import { Component, OnInit, AfterViewInit } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-static-table',
  templateUrl: './static-table.component.html',
  styleUrls: ['./static-table.component.scss']
})
export class StaticTableComponent implements OnInit,AfterViewInit {
  private jsonURL = 'assets/jsonDataTable.json';
  public data: any = [];

  constructor(private router: Router, private http: HttpClient) {}
  ngAfterViewInit(): void {
    console.log('END TIME: ' +new Date().getTime());
  }

  ngOnInit(): void {
    this.http.get(this.jsonURL).subscribe(result => {
      this.data = result;
      console.log('START TIME: ' +new Date().getTime());
    });
  }
}

<h2>Tabela statyczna</h2>
<table>
  <thread>
      <tr>
          <th>Id</th>
          <th>Imie</th>
          <th>Nazwisko</th>
          <th>email</th>
          <th>Gender</th>
          <th>ip_address</th>
        </tr>
  </thread>
  <tbody>
      <tr *ngFor="let el of data">
          <td>{{ el.id }}</td>
          <td>{{ el.Imie }}</td>
          <td>{{ el.Nazwisko }}</td>
          <td>{{ el.email }}</td>
          <td>{{ el.gender }}</td>
          <td>{{ el.ip_address }}</td>
      </tr>
  </tbody>

</table>

// FrontReact/front/src/Components/StaticTable.jsx
import React, { Component } from 'react';
import '../App.css';
import data from './data/jsonDataTable.json';

class StaticTable extends Component {
  constructor()
  {
    console.log('Start: ' + Date.now());
    super()
    this.state = {};
  }

  componentDidMount(){
    console.log('Finish: ' + Date.now())
  }
 

  render() {
    const elementRender = data.map((item, i) => (
      <tr key={item.id}>
        <td>{item.id}</td>
        <td>{item.Imie}</td>
        <td>{item.Nazwisko}</td>
        <td>{item.email}</td>
        <td>{item.gender}</td>
        <td>{item.ip_address}</td>
      </tr>
    ));
    return (
      <div className='static-table-div'>
        <table>
          <thead>
            <th>Id</th>
            <th>Imie</th>
            <th>Nazwisko</th>
            <th>email</th>
            <th>gender</th>
            <th>ip_address</th>
          </thead>
          {elementRender}
        </table>
      </div>
    );
  }
}

export default StaticTable;
