// FrontReact/front/src/Components/CrudComponent.jsx
import React, { Component } from 'react';
import '../App.css';

class CrudComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      act: 0,
      index: '',
      users: [],
    };
  }

  componentDidMount() {
    this.refs.name.focus();
  }

  addData = (e) => {
    e.preventDefault();
    let users = this.state.users;
    let name = this.refs.name.value;
    let surname = this.refs.surname.value;

    if (this.state.act === 0) {
      let data = {
        name,
        surname: surname,
      };
      console.log(this.state.users);
      users.push(data);
    } else {
      let index = this.state.index;
      users[index].name = name;
      users[index].surname = surname;
    }

    this.setState({
      users: users,
    });

    this.refs.myForm.reset();
    this.refs.name.focus();
  };

  removeData = (i) => {
    let users = this.state.users;
    users.splice(i, 1);
    this.setState({
      datas: users,
    });

    this.refs.myForm.reset();
    this.refs.name.focus();
  };

  editData = (i) => {
    let data = this.state.users[i];
    this.refs.name.value = data.name;
    this.refs.surname.value = data.surname;

    this.setState({
      act: 1,
      index: i,
    });
    this.refs.name.focus();
  };

  render() {
    return (
      <div>
        <h2>Lista użytkowników</h2>
        <form ref='myForm'>
          <input type='text' ref='name' placeholder='twoje imie' />
          <input type='text' ref='surname' placeholder='twoje nazwisko' />
          <button onClick={(e) => this.addData(e)}>Dodaj</button>
        </form>
        <pre>
          {this.state.users.map((user, i) => (
            <div key={i} className='div-user'>
              <p className=''>
                {i + 1}.{user.name}, {user.surname}
              </p>
              <button onClick={() => this.removeData(i)}>Usuń</button>
              <button onClick={() => this.editData(i)}>Modyfikuj</button>
            </div>
          ))}
        </pre>
      </div>
    );
  }
}

export default CrudComponent;

// FrontAngular/src/app/table/crud/crud.component.ts
import { Component, OnInit } from '@angular/core';
import {  User } from 'src/app/shared/models/user.model';
import { Router } from '@angular/router';

@Component({
  selector: 'app-crud',
  templateUrl: './crud.component.html',
  styleUrls: ['./crud.component.scss'],
})
export class CrudComponent implements OnInit {
  public list: User[]= [];
  protected newUser: User;
  protected index;

  constructor(private router: Router) {
  }

  ngOnInit(): void {
    
  }

  public add($event,name: string,surname: string){
    event.stopPropagation();
    event.preventDefault();
    this.newUser = new User;
    this.newUser.name = name;
    this.newUser.surname = surname;
    if(this.index == null){
      
    this.list.push(this.newUser);
    } else{
      this.list[this.index] = this.newUser;
    }
    this.index = null;
    this.newUser = new User();
  }

  public remove(index: number){
    this.list.splice(index,1);
  }

  public edit(index: number){
    let date = this.list[index];
    this.newUser.name= date.name;
    this.newUser.surname = date.surname;
    this.index = index;
  }
}

<div>
  <h2>Lista użytkowników</h2>
  <form ref="myForm">
    <input #nazwa matInput value="" placeholder="twoje imie" />
    <input #surname matInput value="" placeholder="twoje nazwisko" />
    <button (click)="add($event,nazwa.value,surname.value)">Dodaj</button>
  </form>
  <div *ngFor="let e of list;let i = index">
        <div>
          <p>
            {{e.name}}, {{e.surname}}
          </p>
          <button (click)="remove(i)">Usuń</button>
          <button (click)="edit(i)">Modyfikuj</button>
        </div>
    </div>
</div>
